-- 리뷰 요청 업적
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 10, 'REQUESTED_FEEDBACK');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 20, 'REQUESTED_FEEDBACK');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 30, 'REQUESTED_FEEDBACK');

-- 누적 추천 수 업적
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 100, 'CUMULATIVE_LIKES');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 200, 'CUMULATIVE_LIKES');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 300, 'CUMULATIVE_LIKES');

-- 채택률 업적
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 50, 'ADOPTION_RATE');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 55, 'ADOPTION_RATE');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 60, 'ADOPTION_RATE');

-- 연속 답변 업적
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 3, 'CONTINUOUS_ANSWER');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 7, 'CONTINUOUS_ANSWER');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 14, 'CONTINUOUS_ANSWER');

-- 채택 답변 개수 업적
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 10, 'ADOPTION_COUNT');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 30, 'ADOPTION_COUNT');
INSERT IGNORE INTO achievements (created_at, updated_at, is_deleted, description, standard, type)
VALUES ('2024-11-27 00:00:00', '2024-11-27 00:00:00', 'FALSE', '', 50, 'ADOPTION_COUNT');

INSERT IGNORE INTO email_domains (name, domain) VALUES
                                             ('가야대학교', 'kaya.ac.kr'),
                                             ('가천대학교', 'gachon.ac.kr'),
                                             ('가톨릭대학교', 'catholic.ac.kr'),
                                             ('감리교신학대학교', 'mtu.ac.kr'),
                                             ('강남대학교', 'kangnam.ac.kr'),
                                             ('강릉원주대학교', 'gwnu.ac.kr'),
                                             ('강원대학교', 'kangwon.ac.kr'),
                                             ('건국대학교', 'konkuk.ac.kr'),
                                             ('건국대학교(글로컬)', 'kku.ac.kr'),
                                             ('건양대학교', 'konyang.ac.kr'),
                                             ('건양사이버대학교', 'kycu.ac.kr'),
                                             ('경기대학교', 'kyonggi.ac.kr'),
                                             ('경남과학기술대학교', 'gntech.ac.kr'),
                                             ('경남대학교', 'hanma.kr'),
                                             ('경동대학교', 'k1.ac.kr'),
                                             ('경북대학교', 'knu.ac.kr'),
                                             ('경북외국어대학교', 'kufs.ac.kr'),
                                             ('경상대학교', 'gnu.ac.kr'),
                                             ('경성대학교', 'ks.ac.kr'),
                                             ('경운대학교', 'ikw.ac.kr'),
                                             ('경인교육대학교', 'ginue.ac.kr'),
                                             ('경일대학교', 'kiu.kr'),
                                             ('경주대학교', 'gju.ac.kr'),
                                             ('경희대학교', 'khu.ac.kr'),
                                             ('경희사이버대학교', 'khcu.ac.kr'),
                                             ('계명대학교', 'kmu.ac.kr'),
                                             ('고려대학교', 'korea.ac.kr'),
                                             ('고려사이버대학교', 'cuk.edu'),
                                             ('고신대학교', 'kosin.ac.kr'),
                                             ('공주교육대학교', 'gjue.ac.kr'),
                                             ('공주대학교', 'smail.kongju.ac.kr'),
                                             ('가톨릭관동대학교', 'cku.ac.kr'),
                                             ('광신대학교', 'kwangshin.ac.kr'),
                                             ('광운대학교', 'kw.ac.kr'),
                                             ('광주가톨릭대학교', 'kjcatholic.ac.kr'),
                                             ('GIST', 'gist.ac.kr'),
                                             ('광주교육대학교', 'gnue.ac.kr'),
                                             ('광주대학교', 'gwangju.ac.kr'),
                                             ('광주여자대학교', 'kwu.ac.kr'),
                                             ('국민대학교', 'kookmin.ac.kr'),
                                             ('국제사이버대학교', 'gcu.ac.kr'),
                                             ('군산대학교', 'kunsan.ac.kr'),
                                             ('그리스도대학교', 'kcu.ac.kr'),
                                             ('극동대학교', 'kdu.ac.kr'),
                                             ('글로벌사이버대학교', 'global.ac.kr'),
                                             ('금강대학교', 'ggu.ac.kr'),
                                             ('금오공과대학교', 'kumoh.ac.kr'),
                                             ('김천대학교', 'gimcheon.ac.kr'),
                                             ('꽃동네대학교', 'kkot.ac.kr'),
                                             ('나사렛대학교', 'kornu.ac.kr'),
                                             ('남부대학교', 'nambu.ac.kr'),
                                             ('남서울대학교', 'nsu.ac.kr'),
                                             ('단국대학교', 'dankook.ac.kr'),
                                             ('대구가톨릭대학교', 'cu.ac.kr'),
                                             ('DGIST', 'dgist.ac.kr'),
                                             ('대구교육대학교', 'dnue.ac.kr'),
                                             ('대구대학교', 'daegu.ac.kr'),
                                             ('대구사이버대학교', 'dcu.ac.kr'),
                                             ('대구예술대학교', 'dgau.ac.kr'),
                                             ('대구외국어대학교', 'dufs.ac.kr'),
                                             ('대구한의대학교', 'dhu.ac.kr'),
                                             ('대신대학교', 'daeshin.ac.kr'),
                                             ('대전가톨릭대학교', 'dcatholic.ac.kr'),
                                             ('대전대학교', 'edu.dju.ac.kr'),
                                             ('대전신학교', 'daejeon.ac.kr'),
                                             ('대진대학교', 'daejin.ac.kr'),
                                             ('덕성여자대학교', 'duksung.ac.kr'),
                                             ('동국대학교', 'dongguk.edu'),
                                             ('동국대학교(경주)', 'dongguk.ac.kr'),
                                             ('동덕여자대학교', 'dongduk.ac.kr'),
                                             ('동명대학교', 'tu.ac.kr'),
                                             ('동서대학교', 'dongseo.ac.kr'),
                                             ('동신대학교', 'dsu.kr'),
                                             ('동아대학교', 'donga.ac.kr'),
                                             ('동양대학교', 'dyu.ac.kr'),
                                             ('동의대학교', 'deu.ac.kr'),
                                             ('디지털서울문화예술대학교', 'scau.ac.kr'),
                                             ('루터대학교', 'ltu.ac.kr'),
                                             ('명지대학교', 'mju.ac.kr'),
                                             ('목원대학교', 'mokwon.ac.kr'),
                                             ('목포가톨릭대학교', 'mcu.ac.kr'),
                                             ('목포대학교', 'mokpo.ac.kr'),
                                             ('목포해양대학교', 'mmu.ac.kr'),
                                             ('배재대학교', 'pcu.ac.kr'),
                                             ('백석대학교', 'bu.ac.kr'),
                                             ('부경대학교', 'pukyong.ac.kr'),
                                             ('부산가톨릭대학교', 'cup.ac.kr'),
                                             ('부산교육대학교', 'bnue.ac.kr'),
                                             ('부산대학교', 'pusan.ac.kr'),
                                             ('부산디지털대학교', 'bdu.ac.kr'),
                                             ('부산외국어대학교', 'bufs.ac.kr'),
                                             ('부산장신대학교', 'bpu.ac.kr'),
                                             ('사이버한국외국어대학교', 'cufs.ac.kr'),
                                             ('삼육대학교', 'syuin.ac.kr'),
                                             ('상명대학교', 'sangmyung.kr'),
                                             ('상주대학교', 'knu.ac.kr'),
                                             ('상지대학교', 'sangji.ac.kr'),
                                             ('서강대학교', 'sogang.ac.kr'),
                                             ('서경대학교', 'skuniv.ac.kr'),
                                             ('서남대학교', 'seonam.ac.kr'),
                                             ('서울과학기술대학교', 'seoultech.ac.kr'),
                                             ('서울교육대학교', 'snue.ac.kr'),
                                             ('서울기독대학교', 'scu.ac.kr'),
                                             ('서울대학교', 'snu.ac.kr'),
                                             ('서울디지털대학교', 'sdu.ac.kr'),
                                             ('서울사이버대학교', 'iscu.ac.kr'),
                                             ('서울시립대학교', 'uos.ac.kr'),
                                             ('서울신학대학교', 'stu.ac.kr'),
                                             ('서울여자대학교', 'swu.ac.kr'),
                                             ('서울장신대학교', 'sjs.ac.kr'),
                                             ('서원대학교', 'seowon.ac.kr'),
                                             ('선문대학교', 'sunmoon.ac.kr'),
                                             ('성결대학교', 'sungkyul.ac.kr'),
                                             ('성공회대학교', 'skhu.ac.kr'),
                                             ('성균관대학교', 'skku.edu'),
                                             ('성신여자대학교', 'sungshin.ac.kr'),
                                             ('세명대학교', 'semyung.ac.kr'),
                                             ('세종대학교', 'sju.ac.kr'),
                                             ('세종사이버대학교', 'sjcu.ac.kr'),
                                             ('세한대학교', 'sehan.ac.kr'),
                                             ('송원대학교', 'songwon.ac.kr'),
                                             ('수원가톨릭대학교', 'suwoncatholic.ac.kr'),
                                             ('수원대학교', 'suwon.ac.kr'),
                                             ('숙명여자대학교', 'sookmyung.ac.kr'),
                                             ('순복음총회신학교', 'kcc.ac.kr'),
                                             ('순천대학교', 'scnu.ac.kr'),
                                             ('순천향대학교', 'sch.ac.kr'),
                                             ('숭실대학교', 'soongsil.ac.kr'),
                                             ('숭실사이버대학교', 'kcu.ac'),
                                             ('신경대학교', 'sgu.ac.kr'),
                                             ('신라대학교', 'silla.ac.kr'),
                                             ('아세아연합신학대학교', 'acts.ac.kr'),
                                             ('아주대학교', 'ajou.ac.kr'),
                                             ('안동대학교', 'anu.ac.kr'),
                                             ('안양대학교', 'ayum.anyang.ac.kr'),
                                             ('연세대학교', 'yonsei.ac.kr'),
                                             ('열린사이버대학교', 'ocu.ac.kr'),
                                             ('영남대학교', 'ynu.ac.kr'),
                                             ('영남신학대학교', 'ytus.ac.kr'),
                                             ('유원대학교', 'u1.ac.kr'),
                                             ('영산대학교', 'ysu.ac.kr'),
                                             ('영산대학교(산업대)', 'ysu.ac.kr'),
                                             ('영산선학대학교', 'youngsan.ac.kr'),
                                             ('예수대학교', 'jesus.ac.kr'),
                                             ('예원예술대학교', 'yewon.ac.kr'),
                                             ('용인대학교', 'yiu.ac.kr'),
                                             ('우석대학교', 'woosuk.ac.kr'),
                                             ('우송대학교', 'wsu.ac.kr'),
                                             ('UNIST', 'unist.ac.kr'),
                                             ('울산대학교', 'ulsan.ac.kr'),
                                             ('원광대학교', 'wonkwang.ac.kr'),
                                             ('원광디지털대학교', 'wdu.ac.kr'),
                                             ('위덕대학교', 'uu.ac.kr'),
                                             ('을지대학교', 'eulji.ac.kr'),
                                             ('이화여자대학교', 'ewhain.net'),
                                             ('인제대학교', 'inje.ac.kr'),
                                             ('인천가톨릭대학교', 'iccu.ac.kr'),
                                             ('인천대학교', 'inu.ac.kr'),
                                             ('인하대학교', 'inha.edu'),
                                             ('장로회신학대학교', 'pcts.ac.kr'),
                                             ('전남대학교', 'jnu.ac.kr'),
                                             ('전북대학교', 'jbnu.ac.kr'),
                                             ('전주교육대학교', 'jnue.kr'),
                                             ('전주대학교', 'jj.ac.kr'),
                                             ('정석대학', 'jit.ac.kr'),
                                             ('제주교육대학교', 'jejue.ac.kr'),
                                             ('제주국제대학교', 'jeju.ac.kr'),
                                             ('제주대학교', 'jejunu.ac.kr'),
                                             ('조선대학교', 'chosun.kr'),
                                             ('중부대학교', 'jmail.ac.kr'),
                                             ('중앙대학교', 'cau.ac.kr'),
                                             ('중앙승가대학교', 'sangha.ac.kr'),
                                             ('중원대학교', 'jwu.ac.kr'),
                                             ('진주교육대학교', 'cue.ac.kr'),
                                             ('진주산업대학교(산업대)', 'gntech.ac.kr'),
                                             ('차의과학대학교', 'cha.ac.kr'),
                                             ('창신대학교', 'cs.ac.kr'),
                                             ('창원대학교', 'changwon.ac.kr'),
                                             ('청운대학교', 'chungwoon.ac.kr'),
                                             ('청주교육대학교', 'cje.ac.kr'),
                                             ('청주대학교', 'cju.ac.kr'),
                                             ('초당대학교', 'chodang.ac.kr'),
                                             ('총신대학교', 'chongshin.ac.kr'),
                                             ('추계예술대학교', 'chugye.ac.kr'),
                                             ('춘천교육대학교', 'cnue.ac.kr'),
                                             ('충남대학교', 'cnu.ac.kr'),
                                             ('충북대학교', 'chungbuk.ac.kr'),
                                             ('침례신학대학교', 'kbtus.ac.kr'),
                                             ('칼빈대학교', 'calvin.ac.kr'),
                                             ('탐라대학교', 'tnu.ac.kr'),
                                             ('평택대학교', 'ptu.ac.kr'),
                                             ('POSTECH', 'postech.ac.kr'),
                                             ('한경대학교', 'hknu.ac.kr'),
                                             ('KAIST', 'kaist.ac.kr'),
                                             ('한국교원대학교', 'knue.ac.kr'),
                                             ('한국교통대학교', 'ut.ac.kr'),
                                             ('한국국제대학교', 'iuk.ac.kr'),
                                             ('한국기술교육대학교', 'koreatech.ac.kr'),
                                             ('한국방송통신대학교', 'knou.ac.kr'),
                                             ('한국산업기술대학교', 'kpu.ac.kr'),
                                             ('한국성서대학교', 'bible.ac.kr'),
                                             ('한국예술종합학교', 'karts.ac.kr'),
                                             ('한국외국어대학교', 'hufs.ac.kr'),
                                             ('한국전통문화대학교', 'nuch.ac.kr'),
                                             ('한국체육대학교', 'knsu.ac.kr'),
                                             ('한국항공대학교', 'kau.kr'),
                                             ('한국해양대학교', 'kmou.ac.kr'),
                                             ('한남대학교', 'hannam.ac.kr'),
                                             ('한동대학교', 'handong.edu'),
                                             ('한라대학교', 'halla.ac.kr'),
                                             ('한려대학교', 'hanlyo.ac.kr'),
                                             ('한림대학교', 'hallym.ac.kr'),
                                             ('한민학교', 'hanmin.ac.kr'),
                                             ('한밭대학교', 'hanbat.ac.kr'),
                                             ('한북대학교', 'hanbuk.ac.kr'),
                                             ('한서대학교', 'hanseo.ac.kr'),
                                             ('한성대학교', 'hansung.ac.kr'),
                                             ('한세대학교', 'uohs.ac.kr'),
                                             ('한신대학교', 'hs.ac.kr'),
                                             ('한양대학교', 'hanyang.ac.kr'),
                                             ('한양사이버대학교', 'hycu.ac.kr'),
                                             ('한영신학대학교', 'hytu.ac.kr'),
                                             ('한일장신대학교', 'hanil.ac.kr'),
                                             ('한중대학교', 'hanzhong.ac.kr'),
                                             ('협성대학교', 'uhs.ac.kr'),
                                             ('호남대학교', 'honam.ac.kr'),
                                             ('호남신학대학교', 'htus.ac.kr'),
                                             ('호서대학교', 'hoseo.edu'),
                                             ('호원대학교', 'howon.ac.kr'),
                                             ('홍익대학교', 'hongik.ac.kr'),
                                             ('화신사이버대학교', 'hscu.ac.kr');
